name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-cloud-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      cloud-available: ${{ steps.check-cloud.outcome == 'success' && 'true' || 'false' }}
    steps:
      - name: Check Cloud Runner
        id: check-cloud
        run: |
          echo "Cloud runner is available."

  build-docker:
    needs: check-cloud-runner
    runs-on: ${{ needs.check-cloud-runner.outputs.cloud-available == 'true' && 'ubuntu-latest' || 'self-hosted' }}
    steps:
      - name: Determine Runner Type
        run: |
          echo "Running build-docker on: ${{ needs.check-cloud-runner.outputs.cloud-available == 'true' && 'cloud' || 'local' }}"

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Build
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/huhunene:latest \
            --cache-to=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/huhunene:latest,mode=max \
            -t ${{ secrets.DOCKER_USERNAME }}/huhunene:latest \
            --push .

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'  # Use the Go version you needs
          
      - name: Websentry Action
        uses: theritikchoure/websentry@main
        with:
          website-url: '24h.com.vn'  # Set the website URLs you want to check
          max-retries: '10'
          retry-interval: '5s'
          request-timeout: '10s'
    